### ISSUE TITLE
API in content scripts

### ISSUE THREAD

**Issue by NiklasGollenstede** [aswan/webext-experiment-hello#1]
Is there already a way to implement APIs for content scripts?
Adding `"allowedContexts": ["content"],` to the `schema.json` adds the interface in content scripts, but calling it throws `not implemented`.
The `api.js` is never loaded in the frame processes.

**Comment by aswan** [comment]
There is not yet a way to do so.  There are a few other related issues with upcoming work for out-of-process extensions.  We'll be creating bugs for these over in bugzilla at some point, I would suggest watching the "WebExtensions: Experiments" component there if you're interested in this work.

**Comment by NiklasGollenstede** [comment]
Oh well, ...
Thanks for the info anyway!
