### ISSUE TITLE
Error loading temporary add-on

### ISSUE THREAD

**Issue by taunosiitam** [aswan/webext-experiment-hello#5]
It's not very encouraging to see a similar issue listed here from the end of the October already, but I report my problem anyway.

Tried to load experiments API add-on with 57.0.2 and got the following error:
`There was an error during installation: Add-on simple@experiments.addons.mozilla.org is not compatible with application version. add-on minVersion: 48.0. add-on maxVersion: *.`

The same error I got with 58.0b10 and latest nightly 59.0a1.

Then I tried 56.0.2 and 55.0.3 and it worked with both of them.

54 and below gave another error:
`There was an error during installation: Install manifest specifies unknown type: null`

What must one do to get the add-on working with current versions?

**Comment by aswan** [comment]
You can't currently load experiments into release, you can load them in Nightly after setting the preference `extensions.legacy.enabled` to true.

**Comment by taunosiitam** [comment]
Works like a charm both in 58.0b10 developer edition and 59.0a1 nightly, thank you!
